collections:
  footer_projects:
  publications:
    output: true
  
permalink: pretty

plugins:
  - jekyll-redirect-from

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge