collections:
  footer_projects:
  publications:
    output: true
  
permalink: pretty

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

author: Daniel Fett

title: 'danielfett.de'

url: 'https://danielfett.de'

excerpt_separator: '<!--more-->'
feed:
  excerpt_only: true

